[build]
publish = "packages/2024lol/dist"
command = "cd packages/2024lol; yarn; yarn build:web"

[build.environment]
HUGO_VERSION = "0.121.2"
GO_VERSION = "1.20.5"

[context.production.environment]
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"


[context.deploy-preview.environment]
HUGO_ENV = "staging"
HUGO_ENABLEGITINFO = "true"
